spring:
  data:
    redis:
      host: 192.168.1.12
      port: 5782
      password:
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            # 允许请求中携带的头信息
            allowedHeaders: "*"
            # 运行跨域的请求方式
            allowedMethods: "*"
            # 跨域检测的有效期,单位s
            maxAge: 36000
      routes:
        # 认证中心
        - id: ruoyi-auth
          uri: lb://ruoyi-auth
          predicates:
            - Path=/auth/**
          filters:
            # 验证码处理
            - CacheRequestFilter
            - ValidateCodeFilter
            - StripPrefix=1
        # 代码生成
        - id: ruoyi-gen
          uri: lb://ruoyi-gen
          predicates:
            - Path=/code/**
          filters:
            - StripPrefix=1
        # 定时任务
        - id: ruoyi-job
          uri: lb://ruoyi-job
          predicates:
            - Path=/schedule/**
          filters:
            - StripPrefix=1
        # 系统模块
        - id: ruoyi-system
          uri: lb://ruoyi-system
          predicates:
            - Path=/system/**
          filters:
            - StripPrefix=1
        # 文件服务
        - id: ruoyi-file
          uri: lb://ruoyi-file
          predicates:
            - Path=/file/**
          filters:
            - StripPrefix=1
        # 商品服务
        - id: pocket-product
          uri: lb://pocket-product
          predicates:
            - Path=/product/**
          filters:
            - StripPrefix=1
        # 会员服务
        - id: pocket-user
          uri: lb://pocket-user
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1            
        # 订单服务
        - id: pocket-order
          uri: lb://pocket-order
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1
        # 频道页服务
        - id: pocket-channel
          uri: lb://pocket-channel
          predicates:
            - Path=/channel/**
          filters:
            - StripPrefix=1  
        - id: pocket-cart
          uri: lb://pocket-cart
          predicates:
            - Path=/cart/**
          filters:
            - StripPrefix=1

        # 支付服务
        - id: pocket-payment
          uri: lb://pocket-payment
          predicates:
            - Path=/payment/**
          filters:
            - StripPrefix=1   
                
        - id: minio-proxy
          uri: http://192.168.1.12:5787
          predicates:
            - Path=/minio/**
          filters:
            - StripPrefix=1

        # AI服务
        - id: pocket-aiAgent
          uri: lb://pocket-aiAgent
          predicates:
            - Path=/aiAgent/**
          filters:
            - StripPrefix=1   
        # 推荐服务
        - id: pocket-recommendation
          uri: lb://pocket-recommendation
          predicates:
            - Path=/recommendation/**
          filters:
            - StripPrefix=1   

        # 直播模块路由
        - id: pocket-live
          uri: lb://pocket-live
          predicates:
            - Path=/live/**
          filters:
            - StripPrefix=1
        # 直播WebSocket路由
        - id: pocket-live-websocket
          uri: ws://192.168.1.12:9213
          predicates:
            - Path=/live/ws/**,/live/live/signaling/**
          filters:
            - StripPrefix=1
        # 直播WebView路由
        - id: pocket-live-webView
          uri: http://192.168.47.1:90
          predicates:
            - Path=/webView/**
          filters:
            - StripPrefix=1


# 安全配置
security:
  # 验证码
  captcha:
    enabled: true
    type: math
  # 防止XSS攻击
  xss:
    enabled: true
    excludeUrls:
      - /system/notice
  # 不校验白名单
  ignore:
    whites:
      - /auth/logout
      - /auth/login
      - /auth/register
      - /*/v2/api-docs
      - /csrf
      - /channel/**
      - /auth/h5/**
      - /user/sms/**
      - /payment/alipay/callback/*
      - /channel/item/goods/**
      - /minio/**
      - /aiAgent/**
      - /live/**
      - /webView/**